version: "2"

run:
  allow-parallel-runners: true

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - unconvert
    - unparam
    - goconst
    - prealloc
    - revive

  settings:
    revive:
      rules:
        - name: blank-imports
        - name: context-as-argument
        - name: context-keys-type
        - name: dot-imports
        - name: error-return
        - name: error-strings
        - name: error-naming
        - name: exported
        - name: increment-decrement
        - name: var-naming
        - name: var-declaration
        - name: package-comments
        - name: range
        - name: receiver-naming
        - name: time-naming
        - name: unexported-return
        - name: indent-error-flow
        - name: errorf
        - name: empty-block
        - name: superfluous-else
        - name: unreachable-code

    goconst:
      min-len: 3
      min-occurrences: 3

  exclusions:
    rules:
      # Exclude some linters from running on test files.
      - path: _test\.go
        linters:
          - errcheck
          - goconst
      # Allow the 'common' package name despite var-naming rule.
      - text: "avoid meaningless package names"
        linters:
          - revive

formatters:
  enable:
    - gofmt
    - goimports

  settings:
    goimports:
      local-prefixes:
        - github.com/guided-traffic/valkey-operator
        - goconst
