package controller

import (
	"context"
	"crypto/tls"
	"fmt"
	"testing"
	"time"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	appsv1 "k8s.io/api/apps/v1"
	corev1 "k8s.io/api/core/v1"
	apierrors "k8s.io/apimachinery/pkg/api/errors"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/types"
	"sigs.k8s.io/controller-runtime/pkg/client"
	"sigs.k8s.io/controller-runtime/pkg/client/interceptor"

	vkov1 "github.com/guided-traffic/valkey-operator/api/v1"
	"github.com/guided-traffic/valkey-operator/internal/builder"
	"github.com/guided-traffic/valkey-operator/internal/common"
	"github.com/guided-traffic/valkey-operator/internal/health"
	"github.com/guided-traffic/valkey-operator/internal/valkeyclient"
)

// The tests in this file pin ADR 0011 D1: once the rolling-update state annotation is
// cleared, nothing else re-detects a second master, and the -rw Service routes
// writes to every pod the sidecar labels master. The steady-state check closes
// that gap -- but a demotion is a REPLICAOF, which discards a dataset, so it never
// acts on the known-master annotation alone. The annotation is unreliable in
// exactly one way: the sidecar drain handler promotes a replica on SIGTERM and has
// no CR access to record it.
//
// Three pieces of evidence separate that promotion from a pod that gave itself the
// role, and every row below is one cell of the decision table they produce:
//
//   - the drain stamp (common.AnnotationDrainPromotedAt), written by the handler
//     onto the pod it promoted;
//   - the structural rule: the init script grants the master config to ordinal 0 or
//     to the pod the replica ConfigMap names, so a labeled master with ordinal > 0
//     that the ConfigMap does not name cannot have elected itself;
//   - the recorded pod's own answer: the pod the annotation names reports a role
//     other than master, so it has already given up whatever dataset it held.
//
// No row may REQUIRE a stamp to reach a safe outcome: during an operator upgrade old
// sidecars keep running and write none. The structural rule alone cannot carry that
// window either -- it can never exonerate pod-0, and pod-0 is exactly the pod a drain
// promotes, since the sidecar walks the ordinals ascending -- so the recorded pod's
// answer carries every cluster whose master is not pod-0, which after one adoption is
// all of them.
//
// The creation order is a fourth signal and it appears on the demotion side only. It
// may refuse, never adopt, and it expires: see recreatedAfter and the two tests that
// bracket its freshness window.

// masterLabeledPod builds a ready pod carrying the full label set the -rw Service
// selects on, i.e. what the sidecar leaves behind after labeling a pod.
func masterLabeledPod(v *vkov1.Valkey, ordinal int, role string) *corev1.Pod {
	name := fmt.Sprintf("%s-%d", v.Name, ordinal)
	pod := &corev1.Pod{
		ObjectMeta: metav1.ObjectMeta{
			Name:      name,
			Namespace: v.Namespace,
			Labels:    common.PodLabels(v, common.ComponentValkey, name, role, nil),
		},
		Status: corev1.PodStatus{
			Phase:      corev1.PodRunning,
			Conditions: []corev1.PodCondition{{Type: corev1.PodReady, Status: corev1.ConditionTrue}},
		},
	}
	ownedByTestSts(v, common.ComponentValkey, pod)
	return pod
}

// drainStamped adds what internal/sidecar/drain.go stamps onto the pod it promoted
// on SIGTERM.
func drainStamped(pod *corev1.Pod) *corev1.Pod {
	return stampedAt(pod, time.Now().UTC().Format(time.RFC3339))
}

// createdAt back-dates a pod by age. Creation order decides whether a demotion is
// refused, so a fixture that leaves it at zero pins nothing: zero ties with zero, the
// rule stays inert, and the test passes for a reason no cluster ever has. Every
// fixture that reaches refuseDemotion therefore carries realistic ages.
func createdAt(pod *corev1.Pod, age time.Duration) *corev1.Pod {
	pod.CreationTimestamp = metav1.NewTime(time.Now().Add(-age).Truncate(time.Second))
	return pod
}

func stampedAt(pod *corev1.Pod, stamp string) *corev1.Pod {
	if pod.Annotations == nil {
		pod.Annotations = map[string]string{}
	}
	pod.Annotations[common.AnnotationDrainPromotedAt] = stamp
	return pod
}

// replicaConfigMapNaming builds the live replica ConfigMap the operator publishes
// when the known master is the given ordinal -- generated by the builder, so the
// parse under test runs against the real file content the init script reads.
func replicaConfigMapNaming(v *vkov1.Valkey, masterOrdinal int) *corev1.ConfigMap {
	published := v.DeepCopy()
	published.Annotations = map[string]string{
		builder.AnnotationKnownMaster: podHost(v.Name, masterOrdinal),
	}
	cm := builder.BuildReplicaConfigMap(published)
	controllerRefTo(v, cm)
	return cm
}

// splitBrainFixture builds the post-failover shape: a 2-replica non-Sentinel CR
// whose known-master annotation names pod-1, with both pods labeled master.
//
// The ages are the ordinary history of a long-running cluster: both pods were
// rescheduled at some point, pod-1 more recently than pod-0. That order is permanent
// once it exists, so it is exactly the input the creation-order refusal must NOT
// react to weeks later -- and with both timestamps left at zero no test in this file
// would have noticed that it did.
func splitBrainFixture() (*vkov1.Valkey, []client.Object) {
	v := newTestValkey("test", testNamespace, func(v *vkov1.Valkey) {
		v.Spec.Replicas = 2
		v.Annotations = map[string]string{
			builder.AnnotationKnownMaster: podHost("test", 1),
		}
	})
	return v, withDataStatefulSet([]client.Object{
		v,
		createdAt(masterLabeledPod(v, 0, common.RoleMaster), 12*24*time.Hour),
		createdAt(masterLabeledPod(v, 1, common.RoleMaster), 9*24*time.Hour),
	})
}

// steadyStateFixture builds a non-Sentinel CR of the given size whose known-master
// annotation names knownOrdinal, and hands back everything a test needs to add pods
// and ConfigMaps of its own.
func steadyStateFixture(replicas, knownOrdinal int) *vkov1.Valkey {
	return newTestValkey("test", testNamespace, func(v *vkov1.Valkey) {
		v.Spec.Replicas = int32(replicas) //nolint:gosec // fixture sizes are single digits
		v.Annotations = map[string]string{
			builder.AnnotationKnownMaster: podHost("test", knownOrdinal),
		}
	})
}

// wire builds the reconciler over the fixture objects and returns the CR as the
// API server holds it, i.e. with a resourceVersion the annotation writes need.
// wire builds a reconciler over objs and hands back the CR as the client stores it.
//
// It injects the data StatefulSet when the caller did not stage one. The pod guards
// prove provenance two-hop -- pod -> StatefulSet -> CR -- so without that object every
// pod fixture reads as foreign and gets filtered out before the check under test ever
// sees it (docs/adr/0020-write-only-what-the-operator-owns.md D9). The injected object
// is deliberately minimal: name, namespace, UID and the controller reference, which is
// everything the provenance chain reads and nothing that would pull a test into the
// rolling-update paths.
func wire(t *testing.T, objs ...client.Object) (*ValkeyReconciler, client.Client, *vkov1.Valkey) {
	t.Helper()
	objs = withDataStatefulSet(objs)
	r, c := newTestReconciler(objs...)
	return r, c, crGet(t, c, "test")
}

// withDataStatefulSet appends the minimal owned data StatefulSet unless objs already
// carries one.
func withDataStatefulSet(objs []client.Object) []client.Object {
	var v *vkov1.Valkey
	for _, o := range objs {
		if _, ok := o.(*appsv1.StatefulSet); ok {
			return objs
		}
		if cr, ok := o.(*vkov1.Valkey); ok {
			v = cr
		}
	}
	if v == nil {
		return objs
	}
	sts := &appsv1.StatefulSet{
		ObjectMeta: metav1.ObjectMeta{
			Name:      common.StatefulSetName(v, common.ComponentValkey),
			Namespace: v.Namespace,
			UID:       testStsUID(v, common.ComponentValkey),
		},
	}
	controllerRefTo(v, sts)
	return append(objs, sts)
}

// rolesChecker answers INFO replication from a pod-name -> role map. A name that
// is absent from the map is unreachable. It counts every probe so a test can
// assert that no Valkey connection was opened at all.
type rolesChecker struct {
	mockInstanceChecker
	probes int
}

func newRolesChecker(roles map[string]string) *rolesChecker {
	rc := &rolesChecker{}
	rc.replicationInfoFn = func(podName string) (*valkeyclient.ReplicationInfo, error) {
		rc.probes++
		role, ok := roles[podName]
		if !ok {
			return nil, fmt.Errorf("unreachable: %s", podName)
		}
		return &valkeyclient.ReplicationInfo{Role: role}, nil
	}
	return rc
}

// allMasters is the answer set of a cluster in which every named pod insists it is
// the master -- the split brain the check exists for.
func allMasters(names ...string) map[string]string {
	roles := make(map[string]string, len(names))
	for _, n := range names {
		roles[n] = common.RoleMaster
	}
	return roles
}

// wireDemotionTarget makes every REPLICAOF succeed against a local fake server
// while recording the address the reconciler dialed.
func wireDemotionTarget(t *testing.T, r *ValkeyReconciler, seen *[]string) {
	t.Helper()
	addr := fakeValkeyServer(t)
	r.NewValkeyClientFn = func(target, _ string, _ *tls.Config) *valkeyclient.Client {
		*seen = append(*seen, target)
		return valkeyclient.New(addr)
	}
}

func podAddr(v *vkov1.Valkey, podName string) string {
	return health.PodAddressForComponent(v, podName, common.ComponentValkey, int(builder.ServicePort(v)))
}

func knownMaster(t *testing.T, c client.Client) string {
	t.Helper()
	return crGet(t, c, "test").Annotations[builder.AnnotationKnownMaster]
}

func podStamp(t *testing.T, c client.Client, podName string) string {
	t.Helper()
	pod := &corev1.Pod{}
	require.NoError(t, c.Get(context.Background(),
		types.NamespacedName{Name: podName, Namespace: testNamespace}, pod))
	return pod.Annotations[common.AnnotationDrainPromotedAt]
}

// --- the gates: nothing runs, nothing is probed ---

// Sentinel clusters have their own authority; the sidecar cross-check demotes a
// pod Sentinel disagrees with.
func TestSteadyStateSplitBrain_SkippedWithSentinel(t *testing.T) {
	v, objs := splitBrainFixture()
	v.Spec.Sentinel = &vkov1.SentinelSpec{Enabled: true, Replicas: 3}
	r, _ := newTestReconciler(objs...)
	checker := newRolesChecker(allMasters("test-0", "test-1"))
	r.InstanceChecker = checker

	_, done, err := r.checkSteadyStateSplitBrain(context.Background(), v)

	require.NoError(t, err)
	assert.False(t, done)
	assert.Equal(t, 0, checker.probes)
}

// While the rolling update runs, the state machine owns the topology and produces
// a two-master window on purpose.
func TestSteadyStateSplitBrain_SkippedDuringRollingUpdate(t *testing.T) {
	v, objs := splitBrainFixture()
	v.Annotations[annotationRollingUpdateState] = stateManualFailover
	r, _ := newTestReconciler(objs...)
	checker := newRolesChecker(allMasters("test-0", "test-1"))
	r.InstanceChecker = checker

	_, done, err := r.checkSteadyStateSplitBrain(context.Background(), v)

	require.NoError(t, err)
	assert.False(t, done)
	assert.Equal(t, 0, checker.probes)
}

// Row 1 of the table. No pod is labeled master: checkAndRecoverNoMaster owns that
// state and promotes pod-0. This check must not race it with an adoption of its
// own, and must not probe on the way out.
func TestSteadyStateSplitBrain_NoLabeledMasterIsNotItsToFix(t *testing.T) {
	v := steadyStateFixture(2, 0)
	r, c, v := wire(t, v,
		masterLabeledPod(v, 0, common.RoleReplica),
		masterLabeledPod(v, 1, common.RoleReplica),
	)
	checker := newRolesChecker(allMasters("test-0", "test-1"))
	r.InstanceChecker = checker
	rec := &fakeEventRecorder{}
	r.Recorder = rec

	result, done, err := r.checkSteadyStateSplitBrain(context.Background(), v)

	require.NoError(t, err)
	assert.False(t, done)
	assert.Zero(t, result.RequeueAfter)
	assert.Equal(t, 0, checker.probes, "a cluster with no labeled master is not probed here")
	assert.Empty(t, rec.events)
	assert.Equal(t, podHost("test", 0), knownMaster(t, c))
}

// Row 2, and the cost property: a healthy cluster has exactly one master-labeled
// pod and the annotation names it, so the check must not open a single Valkey
// connection.
//
// It is also the abandoned-restoration end state -- the annotation names the
// promoted replica, which is the sole labeled master -- and that has to stay a
// no-op, adoption included.
func TestSteadyStateSplitBrain_NoopWhenOnlyOneMasterLabeled(t *testing.T) {
	v := steadyStateFixture(2, 1)
	r, c, v := wire(t, v,
		masterLabeledPod(v, 0, common.RoleReplica),
		masterLabeledPod(v, 1, common.RoleMaster),
	)
	checker := newRolesChecker(nil)
	r.InstanceChecker = checker

	result, done, err := r.checkSteadyStateSplitBrain(context.Background(), v)

	require.NoError(t, err)
	assert.False(t, done)
	assert.Zero(t, result.RequeueAfter)
	assert.Equal(t, 0, checker.probes, "the healthy case must not probe any pod")
	assert.Equal(t, podHost("test", 1), knownMaster(t, c),
		"an agreeing annotation must not be rewritten")
}

// --- one labeled master that the annotation does not name ---
//
// On SIGTERM of a master pod the sidecar promotes a replica (internal/sidecar/drain.go).
// The annotation keeps naming the drained pod, so the recorded authority points at
// the pod that does NOT hold the writes of the drain window.

// drainPromotedObjects builds exactly what the sidecar leaves behind in a
// three-replica cluster: the annotation still names pod-0, pod-0 carries the
// draining label the sidecar patched before failing over, pod-1 is the only pod
// labeled master, and pod-2 is the replica the drain handler repointed at pod-1.
func drainPromotedObjects() (*vkov1.Valkey, *corev1.Pod, []client.Object) {
	v := steadyStateFixture(3, 0)
	promoted := masterLabeledPod(v, 1, common.RoleMaster)
	return v, promoted, []client.Object{
		v,
		masterLabeledPod(v, 0, common.RoleDraining),
		promoted,
		masterLabeledPod(v, 2, common.RoleReplica),
	}
}

// Row 5. The stamp is positive evidence of a promotion nobody recorded, so the
// operator adopts the pod holding the drain-window writes -- and spends the
// evidence while doing it.
func TestSteadyStateSplitBrain_AdoptsTheDrainStampedMaster(t *testing.T) {
	_, promoted, objs := drainPromotedObjects()
	drainStamped(promoted)
	r, c, v := wire(t, objs...)
	checker := newRolesChecker(allMasters("test-1"))
	r.InstanceChecker = checker
	rec := &fakeEventRecorder{}
	r.Recorder = rec
	var dialed []string
	wireDemotionTarget(t, r, &dialed)

	result, done, err := r.checkSteadyStateSplitBrain(context.Background(), v)

	require.NoError(t, err)
	assert.False(t, done, "adoption moves no replication state, so the pass continues")
	assert.Zero(t, result.RequeueAfter)
	assert.Empty(t, dialed, "adoption is a record, never a REPLICAOF")
	assert.Equal(t, 1, checker.probes, "only the pod whose label contradicts the annotation is probed")

	assert.Equal(t, podHost("test", 1), knownMaster(t, c),
		"the pod holding every write of the drain window must become the recorded authority")
	assert.Empty(t, podStamp(t, c, "test-1"),
		"a recorded promotion spends the stamp, or a later pass adopts on it again")

	cm := &corev1.ConfigMap{}
	require.NoError(t, c.Get(context.Background(), types.NamespacedName{
		Name: builder.ReplicaConfigMapName(v), Namespace: testNamespace}, cm))
	assert.Contains(t, cm.Data[builder.ValkeyConfigKey], "replicaof "+podHost("test", 1),
		"the returning pod-0 reads the mounted ConfigMap, so it has to move with the annotation")

	adopted := rec.withReason("MasterAdopted")
	require.Len(t, adopted, 1, "a promotion the operator did not perform has to be visible on the CR")
	assert.Equal(t, corev1.EventTypeNormal, adopted[0].eventType)
	assert.Contains(t, adopted[0].note, "test-1")
	assert.Contains(t, adopted[0].note, "test-0")
	assert.Contains(t, adopted[0].note, "stamped")
}

// Row 6, and the whole operator-upgrade window: an old sidecar writes no stamp, so
// the structural rule has to carry the adoption on its own. test-1 has ordinal 1 and
// the replica ConfigMap names test-0, so neither path the init script offers could
// have given test-1 the master role -- somebody promoted it.
//
// This is also attack A1b, the accepted residual: a pod whose sandbox is recreated
// within kubelet's ConfigMap refresh window (~1 min) can self-claim off a mount the
// operator has already replaced, and would be adopted here. Closing it needs the
// init container's finish time against a publish timestamp; the window is bounded
// and needs the real master to be unlabeled at the same instant.
func TestSteadyStateSplitBrain_AdoptsAMasterThatCannotHaveSelfElected(t *testing.T) {
	v, _, objs := drainPromotedObjects()
	r, c, v := wire(t, append(objs, replicaConfigMapNaming(v, 0))...)
	r.InstanceChecker = newRolesChecker(allMasters("test-1"))
	rec := &fakeEventRecorder{}
	r.Recorder = rec

	_, done, err := r.checkSteadyStateSplitBrain(context.Background(), v)

	require.NoError(t, err)
	assert.False(t, done)
	assert.Equal(t, podHost("test", 1), knownMaster(t, c))

	adopted := rec.withReason("MasterAdopted")
	require.Len(t, adopted, 1)
	assert.Contains(t, adopted[0].note, "cannot have given itself the master role")
}

// [REGRESSION] The drain the structural rule cannot see, caught one state earlier
// than the split brain it used to produce.
//
// buildReplicaAddrs walks the ordinals ascending and findSyncedReplica takes the first synced peer,
// so draining a non-pod-0 master promotes pod-0 -- and pod-0 is the one pod couldNotHaveSelfElected
// can never exonerate. With the stamp lost (an old sidecar mid-upgrade, or a rejected patch) the
// operator had no evidence at all and refused, which is worse than it sounds: the annotation and
// the replica ConfigMap keep naming the drained pod, so that pod self-claims off its own mount when
// it returns (docs/adr/0008-known-master-annotation-is-the-recorded-authority.md, D8, D9), and the
// refusal has manufactured a two-master state whose only remaining resolution is another refusal.
//
// The recorded pod's own answer breaks it: test-1 came back, found test-0 serving as
// master and joined it as a replica, so whatever it held it has already given up.
// Adopting test-0 republishes the ConfigMap while test-1 is a replica, so the next
// restart keeps it one.
//
// The evidence is deliberately NOT that test-1 is the newer Pod object, which is also
// true here. TestSteadyStateSplitBrain_DoesNotAdoptASelfElectedPeerWhileTheRecordedMasterIsBooting
// is the same object shape with the opposite correct outcome, which is exactly why
// the creation order may not decide an adoption.
func TestSteadyStateSplitBrain_AdoptsTheMasterTheRecordedPodYieldedTo(t *testing.T) {
	v := steadyStateFixture(2, 1)
	r, c, v := wire(t, v,
		createdAt(masterLabeledPod(v, 0, common.RoleMaster), time.Hour),
		createdAt(masterLabeledPod(v, 1, common.RoleReplica), time.Minute),
		replicaConfigMapNaming(v, 1),
	)
	r.InstanceChecker = newRolesChecker(map[string]string{
		"test-0": common.RoleMaster,
		"test-1": common.RoleReplica,
	})
	rec := &fakeEventRecorder{}
	r.Recorder = rec
	var dialed []string
	wireDemotionTarget(t, r, &dialed)

	_, done, err := r.checkSteadyStateSplitBrain(context.Background(), v)

	require.NoError(t, err)
	assert.False(t, done)
	assert.Empty(t, dialed, "adoption is a record, never a REPLICAOF")
	assert.Equal(t, podHost("test", 0), knownMaster(t, c),
		"the pod that held the master role through the drain window has to become the record")
	assert.Empty(t, rec.withReason("MasterAdoptionRefused"))

	adopted := rec.withReason("MasterAdopted")
	require.Len(t, adopted, 1)
	assert.Contains(t, adopted[0].note, "no longer reports the master role")

	cm := &corev1.ConfigMap{}
	require.NoError(t, c.Get(context.Background(), types.NamespacedName{
		Name: builder.ReplicaConfigMapName(v), Namespace: testNamespace}, cm))
	assert.Contains(t, cm.Data[builder.ValkeyConfigKey], "replicaof "+podHost("test", 0),
		"republishing is what keeps the returning pod from self-claiming off its own mount")
}

// [REGRESSION] The adoption branch used to accept "the recorded pod is the younger
// Pod object" as evidence of a promotion, and that reading destroys the newer
// dataset. No drain occurs anywhere in this path:
//
//   - test-1 is the recorded master and its node hard-fails. No SIGTERM, so the
//     drain handler never runs, nothing is promoted and no stamp is written. The pod
//     is rescheduled and comes back as a strictly newer Pod object, still booting.
//   - test-0's node reboots in the same window. Its init container re-runs, reaches
//     no peer, takes the ordinal fallback and elects itself master. An in-place
//     sandbox recreation leaves the Pod object -- and its creationTimestamp -- alone.
//
// test-0 is then the sole labeled master and test-1 is merely newer, which is
// indistinguishable from a drain by creation order alone. Adopting republished the
// replica ConfigMap toward test-0, and test-1 full-resynced its own newer dataset
// away as soon as it finished booting: silently, and caused by the operator.
//
// The record stays put while the pod it names cannot answer for itself.
func TestSteadyStateSplitBrain_DoesNotAdoptASelfElectedPeerWhileTheRecordedMasterIsBooting(t *testing.T) {
	v := steadyStateFixture(2, 1)
	r, c, v := wire(t, v,
		createdAt(masterLabeledPod(v, 0, common.RoleMaster), 30*24*time.Hour),
		createdAt(masterLabeledPod(v, 1, common.RoleReplica), time.Minute),
		replicaConfigMapNaming(v, 1),
	)
	// test-1 is still booting: it answers nothing.
	r.InstanceChecker = newRolesChecker(allMasters("test-0"))
	rec := &fakeEventRecorder{}
	r.Recorder = rec

	_, done, err := r.checkSteadyStateSplitBrain(context.Background(), v)

	require.NoError(t, err)
	assert.False(t, done)
	assert.Equal(t, podHost("test", 1), knownMaster(t, c),
		"a pod that cannot answer may still hold the newer dataset, so the record stays on it")
	assert.Empty(t, rec.withReason("MasterAdopted"))
	require.Len(t, rec.withReason("MasterAdoptionRefused"), 1)

	cm := &corev1.ConfigMap{}
	require.NoError(t, c.Get(context.Background(), types.NamespacedName{
		Name: builder.ReplicaConfigMapName(v), Namespace: testNamespace}, cm))
	assert.Contains(t, cm.Data[builder.ValkeyConfigKey], "replicaof "+podHost("test", 1),
		"republishing toward test-0 is the write that makes the returning master discard its data")
}

// The same refusal one step earlier, while the recorded pod does not exist at all --
// the window between the delete and the StatefulSet recreating it.
//
// Absence must not read as "it gave up the role" for the same reason the creation
// order must not: it is the sibling above with the Pod object deleted instead of
// rescheduled, and adopting on it republishes the ConfigMap toward a pod that may
// hold the older dataset. The adoption waits for the pod to come back and say so.
func TestSteadyStateSplitBrain_DoesNotAdoptWhileTheRecordedPodIsGone(t *testing.T) {
	v := steadyStateFixture(2, 1)
	r, c, v := wire(t, v,
		createdAt(masterLabeledPod(v, 0, common.RoleMaster), time.Hour),
		replicaConfigMapNaming(v, 1),
	)
	r.InstanceChecker = newRolesChecker(allMasters("test-0"))
	rec := &fakeEventRecorder{}
	r.Recorder = rec

	_, done, err := r.checkSteadyStateSplitBrain(context.Background(), v)

	require.NoError(t, err)
	assert.False(t, done)
	assert.Equal(t, podHost("test", 1), knownMaster(t, c))
	assert.Empty(t, rec.withReason("MasterAdopted"))
	assert.Len(t, rec.withReason("MasterAdoptionRefused"), 1)
}

// The counterpart, and the shape of every completed rolling update: the old master
// pod-0 is deleted last, so it is the NEWEST pod when the update ends. A rogue that
// is younger than the record is not the drain shape, and the annotation still
// decides -- otherwise the rule would refuse on the most common topology there is.
func TestSteadyStateSplitBrain_DemotesARogueYoungerThanTheRecordedMaster(t *testing.T) {
	v := steadyStateFixture(3, 1)
	r, c, v := wire(t, v,
		createdAt(masterLabeledPod(v, 0, common.RoleMaster), time.Minute),
		createdAt(masterLabeledPod(v, 1, common.RoleMaster), time.Hour),
		masterLabeledPod(v, 2, common.RoleReplica),
		replicaConfigMapNaming(v, 1),
	)
	r.InstanceChecker = newRolesChecker(allMasters("test-0", "test-1"))
	rec := &fakeEventRecorder{}
	r.Recorder = rec
	var dialed []string
	wireDemotionTarget(t, r, &dialed)

	_, done, err := r.checkSteadyStateSplitBrain(context.Background(), v)

	require.NoError(t, err)
	assert.True(t, done)
	assert.Equal(t, []string{podAddr(v, "test-0")}, dialed)
	assert.Equal(t, podHost("test", 1), knownMaster(t, c))
	assert.Empty(t, rec.withReason("SplitBrainDemotionRefused"))
}

// Row 7, and attack A9: the drain of pod-2 promoted pod-0, and no stamp survived.
// Ordinal 0 is exactly the ordinal the init script hands the master config to
// unconditionally, so the structural rule says nothing and the operator refuses.
// Its own annotation is left naming test-2.
func TestSteadyStateSplitBrain_RefusesToAdoptOrdinalZero(t *testing.T) {
	v := steadyStateFixture(3, 2)
	r, c, v := wire(t, v,
		masterLabeledPod(v, 0, common.RoleMaster),
		masterLabeledPod(v, 1, common.RoleReplica),
		masterLabeledPod(v, 2, common.RoleReplica),
		replicaConfigMapNaming(v, 2),
	)
	r.InstanceChecker = newRolesChecker(allMasters("test-0"))
	rec := &fakeEventRecorder{}
	r.Recorder = rec

	result, done, err := r.checkSteadyStateSplitBrain(context.Background(), v)

	require.NoError(t, err)
	assert.False(t, done)
	assert.Zero(t, result.RequeueAfter,
		"one labeled master is not a split brain: writes reach one dataset, so polling buys nothing")
	assert.Equal(t, podHost("test", 2), knownMaster(t, c))
	assert.Empty(t, rec.withReason("MasterAdopted"))

	refusals := rec.withReason("MasterAdoptionRefused")
	require.Len(t, refusals, 1, "a record the operator will not correct has to be visible")
	assert.Equal(t, corev1.EventTypeWarning, refusals[0].eventType)
	assert.Contains(t, refusals[0].note, "test-0")
	assert.Contains(t, refusals[0].note, "test-2")
}

// Row 8. The ADR 0008 D8, D9 self-claim: the mounted replica config names this very pod, so
// the init script gave it the master role and nobody promoted it. Adopting would
// bless a pod that may hold the older dataset.
func TestSteadyStateSplitBrain_RefusesToAdoptAPodTheConfigMapNames(t *testing.T) {
	v, _, objs := drainPromotedObjects()
	r, c, v := wire(t, append(objs, replicaConfigMapNaming(v, 1))...)
	r.InstanceChecker = newRolesChecker(allMasters("test-1"))
	rec := &fakeEventRecorder{}
	r.Recorder = rec

	_, done, err := r.checkSteadyStateSplitBrain(context.Background(), v)

	require.NoError(t, err)
	assert.False(t, done)
	assert.Equal(t, podHost("test", 0), knownMaster(t, c))
	assert.Empty(t, rec.withReason("MasterAdopted"))
	assert.Len(t, rec.withReason("MasterAdoptionRefused"), 1)
}

// Row 9, attack A10. The ConfigMap cannot be read, so the structural rule has no
// input. Missing evidence is not evidence: an unreadable ConfigMap must never read
// as "it does not name this pod, therefore adopt".
func TestSteadyStateSplitBrain_RefusesToAdoptWhenTheReplicaConfigMapIsMissing(t *testing.T) {
	_, _, objs := drainPromotedObjects()
	r, c, v := wire(t, objs...)
	r.InstanceChecker = newRolesChecker(allMasters("test-1"))
	rec := &fakeEventRecorder{}
	r.Recorder = rec

	_, done, err := r.checkSteadyStateSplitBrain(context.Background(), v)

	require.NoError(t, err)
	assert.False(t, done)
	assert.Equal(t, podHost("test", 0), knownMaster(t, c))
	assert.Empty(t, rec.withReason("MasterAdopted"))
	assert.Len(t, rec.withReason("MasterAdoptionRefused"), 1)
}

// A stamp is only evidence while it is a timestamp. Anything else reads as no
// stamp, never as "corrupt, therefore fresh" -- the fixture below would be adopted
// on presence alone, and is refused because the value does not parse.
func TestSteadyStateSplitBrain_AnUnparseableStampIsNoStamp(t *testing.T) {
	_, promoted, objs := drainPromotedObjects()
	stampedAt(promoted, "yesterday")
	r, c, v := wire(t, objs...)
	r.InstanceChecker = newRolesChecker(allMasters("test-1"))
	rec := &fakeEventRecorder{}
	r.Recorder = rec

	_, _, err := r.checkSteadyStateSplitBrain(context.Background(), v)

	require.NoError(t, err)
	assert.Equal(t, podHost("test", 0), knownMaster(t, c))
	assert.Len(t, rec.withReason("MasterAdoptionRefused"), 1)
}

// Rows 3 and 4. The probe is what separates a promotion from a stale label: a pod
// that answers role:slave is replicating from somewhere else, and an unreachable
// pod may be one that is itself on the way out.
func TestSteadyStateSplitBrain_DoesNotAdoptAPodThatReportsReplica(t *testing.T) {
	_, promoted, objs := drainPromotedObjects()
	drainStamped(promoted)
	r, c, v := wire(t, objs...)
	r.InstanceChecker = newRolesChecker(map[string]string{"test-1": common.RoleReplica})
	rec := &fakeEventRecorder{}
	r.Recorder = rec

	_, done, err := r.checkSteadyStateSplitBrain(context.Background(), v)

	require.NoError(t, err)
	assert.False(t, done)
	assert.Equal(t, podHost("test", 0), knownMaster(t, c),
		"a stale label is not evidence of a promotion, stamp or no stamp")
	assert.Empty(t, rec.events)
}

func TestSteadyStateSplitBrain_DoesNotAdoptAnUnreachablePod(t *testing.T) {
	_, promoted, objs := drainPromotedObjects()
	drainStamped(promoted)
	r, c, v := wire(t, objs...)
	r.InstanceChecker = newRolesChecker(nil)
	rec := &fakeEventRecorder{}
	r.Recorder = rec

	_, done, err := r.checkSteadyStateSplitBrain(context.Background(), v)

	require.NoError(t, err)
	assert.False(t, done)
	assert.Equal(t, podHost("test", 0), knownMaster(t, c))
	assert.Empty(t, rec.events)
}

// While the rolling update runs, the operator owns the topology and produces
// exactly this shape on purpose on its way through the failover. Adopting there
// would overwrite the authority the state machine is still working from.
func TestSteadyStateSplitBrain_DoesNotAdoptDuringRollingUpdate(t *testing.T) {
	v, promoted, objs := drainPromotedObjects()
	drainStamped(promoted)
	v.Annotations[annotationRollingUpdateState] = stateManualFailover
	r, c, v := wire(t, objs...)
	checker := newRolesChecker(allMasters("test-1"))
	r.InstanceChecker = checker
	rec := &fakeEventRecorder{}
	r.Recorder = rec

	_, done, err := r.checkSteadyStateSplitBrain(context.Background(), v)

	require.NoError(t, err)
	assert.False(t, done)
	assert.Equal(t, 0, checker.probes, "the guard must hold before any probe is opened")
	assert.Equal(t, podHost("test", 0), knownMaster(t, c))
	assert.Empty(t, rec.events)
}

// --- two labeled masters: evidence first, annotation second ---

// The ADR 0011 D1 regression test: no stamp anywhere, the annotation names one of them and
// it confirms role:master, so the other one is demoted toward it. The authority is
// not pod-0, so the missed-drain shape does not apply.
func TestSteadyStateSplitBrain_DemotesConfirmedRogue(t *testing.T) {
	v, objs := splitBrainFixture()
	r, _ := newTestReconciler(objs...)
	r.InstanceChecker = newRolesChecker(allMasters("test-0", "test-1"))
	rec := &fakeEventRecorder{}
	r.Recorder = rec
	var dialed []string
	wireDemotionTarget(t, r, &dialed)

	result, done, err := r.checkSteadyStateSplitBrain(context.Background(), v)

	require.NoError(t, err)
	assert.True(t, done, "a confirmed second master must end the pass")
	assert.Equal(t, steadyStateRecheckDelay, result.RequeueAfter)
	assert.Equal(t, []string{podAddr(v, "test-0")}, dialed,
		"only the rogue master may receive REPLICAOF, never the authority")

	resolved := rec.withReason("SplitBrainResolved")
	require.Len(t, resolved, 1)
	assert.Contains(t, resolved[0].note, "test-0")
	assert.Contains(t, resolved[0].note, "test-1")
	assert.Empty(t, rec.withReason("MasterAdopted"),
		"without a stamp the annotation decides, and it needs no adoption")
}

// [REGRESSION] Row 10, the two-replica missed drain -- the case the whole design
// exists for. pod-0 was drained, its sidecar promoted pod-1 and stamped it, pod-1
// took every write of the drain window, and the returning pod-0 self-claimed off
// the replica ConfigMap (docs/adr/0008-known-master-annotation-is-the-recorded-authority.md, D8,
// D9). The annotation still names pod-0.
//
// Resolving toward the annotation would REPLICAOF pod-1 and discard those writes,
// which is worse than doing nothing at all -- before the steady-state check existed
// the same drain left two visible masters and destroyed neither dataset. The stamp
// resolves it in the correct direction instead.
func TestSteadyStateSplitBrain_RecordsTheStampedMasterAndDemotesTheOthers(t *testing.T) {
	v := steadyStateFixture(2, 0)
	promoted := drainStamped(masterLabeledPod(v, 1, common.RoleMaster))
	r, c, v := wire(t, v,
		masterLabeledPod(v, 0, common.RoleMaster),
		promoted,
		replicaConfigMapNaming(v, 0),
	)
	r.InstanceChecker = newRolesChecker(allMasters("test-0", "test-1"))
	rec := &fakeEventRecorder{}
	r.Recorder = rec
	var dialed []string
	wireDemotionTarget(t, r, &dialed)

	result, done, err := r.checkSteadyStateSplitBrain(context.Background(), v)

	require.NoError(t, err)
	assert.True(t, done)
	assert.Equal(t, steadyStateRecheckDelay, result.RequeueAfter)
	assert.Equal(t, []string{podAddr(v, "test-0")}, dialed,
		"the pod that holds the drain-window writes must be the target, never the demoted one")
	assert.Equal(t, podHost("test", 1), knownMaster(t, c))
	assert.Empty(t, podStamp(t, c, "test-1"))
	require.Len(t, rec.withReason("MasterAdopted"), 1)
	require.Len(t, rec.withReason("SplitBrainResolved"), 1)
}

// [REGRESSION] Attack A2b. Two live stamped masters -- one node hosting both masters
// of an existing split brain, drained at once -- are genuinely ambiguous, and rule 1
// requires exactly one.
//
// The expectation here is the inverse of what it used to be. This test previously
// pinned the fall-through to rule 2, which demoted BOTH stamped pods toward the
// annotation-named pod: ambiguous evidence routed straight past the refusal into the
// most destructive action of the whole file, discarding two drain windows at once
// precisely because nothing said which one mattered. Ambiguous evidence has to end
// in the refusal, so the pass now stops at rule 1 and leaves every dataset intact.
func TestSteadyStateSplitBrain_TwoStampsRefuseInsteadOfConsolidating(t *testing.T) {
	v := steadyStateFixture(4, 1)
	r, c, v := wire(t, v,
		masterLabeledPod(v, 0, common.RoleReplica),
		masterLabeledPod(v, 1, common.RoleMaster),
		drainStamped(masterLabeledPod(v, 2, common.RoleMaster)),
		drainStamped(masterLabeledPod(v, 3, common.RoleMaster)),
	)
	r.InstanceChecker = newRolesChecker(allMasters("test-1", "test-2", "test-3"))
	rec := &fakeEventRecorder{}
	r.Recorder = rec
	var dialed []string
	wireDemotionTarget(t, r, &dialed)

	result, done, err := r.checkSteadyStateSplitBrain(context.Background(), v)

	require.NoError(t, err)
	assert.False(t, done, "nothing was demoted, so the pass must still reach updateStatus")
	assert.Equal(t, steadyStateRecheckDelay, result.RequeueAfter,
		"and an unresolved split brain keeps the recheck cadence")
	assert.NotContains(t, dialed, podAddr(v, "test-2"),
		"neither stamped pod may be demoted: each REPLICAOF would discard a drain window")
	assert.Empty(t, dialed, "and the annotation-named pod is not a target either")
	assert.Equal(t, podHost("test", 1), knownMaster(t, c), "a refusal changes no record")
	assert.Empty(t, rec.withReason("MasterAdopted"))
	assert.NotEmpty(t, podStamp(t, c, "test-2"),
		"the stamps stay: evidence is only spent once the operator recorded something")
	assert.Empty(t, rec.withReason("SplitBrainResolved"))

	refusals := rec.withReason("SplitBrainDemotionRefused")
	require.Len(t, refusals, 1, "the one state with no automatic way out has to be visible")
	assert.Equal(t, corev1.EventTypeWarning, refusals[0].eventType)
	assert.Contains(t, refusals[0].note, "test-2")
	assert.Contains(t, refusals[0].note, "test-3")
}

// Attack A11. Only one of the two labeled masters confirms the role -- the other
// carries a label the sidecar has not repatched yet. The stamped pod is still the
// unambiguous answer, and the stale-labeled pod must not receive a REPLICAOF: it is
// already a replica of somewhere.
func TestSteadyStateSplitBrain_StaleLabelDoesNotBlockTheStampedMaster(t *testing.T) {
	v := steadyStateFixture(2, 0)
	r, c, v := wire(t, v,
		masterLabeledPod(v, 0, common.RoleMaster),
		drainStamped(masterLabeledPod(v, 1, common.RoleMaster)),
	)
	r.InstanceChecker = newRolesChecker(map[string]string{
		"test-0": common.RoleReplica,
		"test-1": common.RoleMaster,
	})
	rec := &fakeEventRecorder{}
	r.Recorder = rec
	var dialed []string
	wireDemotionTarget(t, r, &dialed)

	result, done, err := r.checkSteadyStateSplitBrain(context.Background(), v)

	require.NoError(t, err)
	assert.False(t, done, "nothing was demoted, so the pass continues to updateStatus")
	assert.Zero(t, result.RequeueAfter)
	assert.Empty(t, dialed)
	assert.Equal(t, podHost("test", 1), knownMaster(t, c),
		"the promotion still has to be recorded, or the annotation stays wrong forever")
	assert.Empty(t, podStamp(t, c, "test-1"))
}

// [REGRESSION] Row 13. The same two-replica missed drain as row 10, but the stamp
// never landed -- an operator upgrade in which the old sidecar is still running, or
// a patch the API server rejected. The annotation names pod-0 and pod-1 could not
// have given itself the role, so the shape is the drain and demoting is the
// destructive direction. The operator refuses, and both masters stay visible.
//
// Accepted residual: this refusal also catches a human running REPLICAOF NO ONE on
// pod-1 while pod-0 is healthy (attack A8), and a stale-mount self-claim (A1a).
// Nothing is destroyed there either, but the split brain becomes permanent until a
// human resolves it. The creation-order rule does not narrow this branch -- it adds
// the branch the structural shape misses.
//
// The equal ages are the point of the fixture, not an omission: the data StatefulSet
// runs with PodManagementPolicy: Parallel, so a co-restart recreates both pods at
// once and ties their timestamps. The creation order is strict and therefore inert
// here, and the structural form alone has to produce the refusal.
func TestSteadyStateSplitBrain_RefusesTheMissedDrainShape(t *testing.T) {
	v := steadyStateFixture(2, 0)
	r, c, v := wire(t, v,
		createdAt(masterLabeledPod(v, 0, common.RoleMaster), 6*time.Hour),
		createdAt(masterLabeledPod(v, 1, common.RoleMaster), 6*time.Hour),
		replicaConfigMapNaming(v, 0),
	)
	r.InstanceChecker = newRolesChecker(allMasters("test-0", "test-1"))
	rec := &fakeEventRecorder{}
	r.Recorder = rec
	var dialed []string
	wireDemotionTarget(t, r, &dialed)

	result, done, err := r.checkSteadyStateSplitBrain(context.Background(), v)

	require.NoError(t, err)
	assert.Empty(t, dialed, "REPLICAOF on test-1 would full-resync the drain-window writes away")
	assert.Empty(t, rec.withReason("SplitBrainResolved"))

	refusals := rec.withReason("SplitBrainDemotionRefused")
	require.Len(t, refusals, 1, "a refusal the operator cannot resolve has to be visible")
	assert.Equal(t, corev1.EventTypeWarning, refusals[0].eventType)
	assert.Contains(t, refusals[0].note, "test-0", "the Event must name the recorded master")
	assert.Contains(t, refusals[0].note, "test-1", "and the pod it refused to demote")

	assert.False(t, done, "the refusal must not suppress updateStatus")
	assert.Equal(t, steadyStateRecheckDelay, result.RequeueAfter,
		"and it must keep the recheck cadence, like any other unresolved split brain")
	assert.Equal(t, podHost("test", 0), knownMaster(t, c),
		"refusing changes no state at all, the annotation included")
}

// [REGRESSION] The same missed drain one state later, on the topology this design
// routinely produces: the master is test-1 (every adoption leaves a non-pod-0 master
// behind), its node is drained, the sidecar promotes test-0 and the stamp is lost,
// test-1 returns and self-claims off the ConfigMap that still names it.
//
// The structural rule is inert here by construction -- the rogue is test-0, and
// ordinal 0 is exactly what couldNotHaveSelfElected refuses to exonerate -- and the
// old predicate additionally required the authority to BE pod-0, which it is not. So
// the operator sent REPLICAOF to test-0, the pod holding every write of the drain
// window, and the dataset was gone. The creation order is the only thing that
// separates the two pods, and it does: test-1 was recreated, test-0 was not.
func TestSteadyStateSplitBrain_RefusesWhenTheRecordedMasterIsNewer(t *testing.T) {
	v := steadyStateFixture(2, 1)
	r, c, v := wire(t, v,
		createdAt(masterLabeledPod(v, 0, common.RoleMaster), time.Hour),
		createdAt(masterLabeledPod(v, 1, common.RoleMaster), time.Minute),
		replicaConfigMapNaming(v, 1),
	)
	r.InstanceChecker = newRolesChecker(allMasters("test-0", "test-1"))
	rec := &fakeEventRecorder{}
	r.Recorder = rec
	var dialed []string
	wireDemotionTarget(t, r, &dialed)

	result, done, err := r.checkSteadyStateSplitBrain(context.Background(), v)

	require.NoError(t, err)
	assert.Empty(t, dialed, "REPLICAOF on test-0 would full-resync the drain-window writes away")
	assert.False(t, done, "the refusal must not suppress updateStatus")
	assert.Equal(t, steadyStateRecheckDelay, result.RequeueAfter)
	assert.Equal(t, podHost("test", 1), knownMaster(t, c), "refusing changes no state at all")
	assert.Empty(t, rec.withReason("SplitBrainResolved"))

	refusals := rec.withReason("SplitBrainDemotionRefused")
	require.Len(t, refusals, 1)
	assert.Equal(t, corev1.EventTypeWarning, refusals[0].eventType)
	assert.Contains(t, refusals[0].note, "test-1 was created after test-0",
		"the Event has to say which evidence produced the refusal")
}

// [REGRESSION] The same shape as the test above with one thing changed: the
// recreation is old. The creation order compared absolute timestamps with no
// recency window, so "the recorded pod is the younger object" -- permanent from the
// first reschedule onwards -- refused every later split brain of that pair for the
// life of the cluster, whatever its cause. The refusal is about a drain that just
// happened, so it has to expire with the recreation that produced it.
//
// 20 days is far past v.GetSyncTimeout() (default 5m, the operator's own budget for
// a deleted pod to rejoin its master), so the annotation decides again, exactly as it
// did before the creation-order rule existed.
func TestSteadyStateSplitBrain_AnAncientRecreationNoLongerRefusesTheDemotion(t *testing.T) {
	v := steadyStateFixture(2, 1)
	r, c, v := wire(t, v,
		createdAt(masterLabeledPod(v, 0, common.RoleMaster), 30*24*time.Hour),
		createdAt(masterLabeledPod(v, 1, common.RoleMaster), 20*24*time.Hour),
		replicaConfigMapNaming(v, 1),
	)
	r.InstanceChecker = newRolesChecker(allMasters("test-0", "test-1"))
	rec := &fakeEventRecorder{}
	r.Recorder = rec
	var dialed []string
	wireDemotionTarget(t, r, &dialed)

	_, done, err := r.checkSteadyStateSplitBrain(context.Background(), v)

	require.NoError(t, err)
	assert.True(t, done, "a resolvable split brain must be resolved, not refused forever")
	assert.Equal(t, []string{podAddr(v, "test-0")}, dialed)
	assert.Equal(t, podHost("test", 1), knownMaster(t, c))
	assert.Empty(t, rec.withReason("SplitBrainDemotionRefused"))
	assert.Len(t, rec.withReason("SplitBrainResolved"), 1)
}

// Attack A10 on the destructive side. The replica ConfigMap cannot be read, so the
// operator cannot tell the missed drain from a self-claim -- and a REPLICAOF needs
// positive justification, not the absence of a counter-argument.
func TestSteadyStateSplitBrain_RefusesToDemoteWhenTheReplicaConfigMapIsMissing(t *testing.T) {
	v := steadyStateFixture(2, 0)
	r, c, v := wire(t, v,
		createdAt(masterLabeledPod(v, 0, common.RoleMaster), 4*24*time.Hour),
		createdAt(masterLabeledPod(v, 1, common.RoleMaster), 4*24*time.Hour),
	)
	r.InstanceChecker = newRolesChecker(allMasters("test-0", "test-1"))
	rec := &fakeEventRecorder{}
	r.Recorder = rec
	var dialed []string
	wireDemotionTarget(t, r, &dialed)

	result, done, err := r.checkSteadyStateSplitBrain(context.Background(), v)

	require.NoError(t, err)
	assert.Empty(t, dialed)
	assert.False(t, done)
	assert.Equal(t, steadyStateRecheckDelay, result.RequeueAfter)
	assert.Len(t, rec.withReason("SplitBrainDemotionRefused"), 1)
	assert.Equal(t, podHost("test", 0), knownMaster(t, c))
}

// Row 14. The rogue is pod-0 itself, which is the one ordinal the init script hands
// the master config to unconditionally -- the ordinal fallback after peer discovery
// timed out. Nothing about that shape says a drain happened, so the annotation
// decides, exactly as it did before the stamp existed.
//
// The ages are load-bearing and were the false negative that hid the unbounded
// creation-order rule: with every timestamp left at zero the comparison tied, the
// rule stayed inert and this test passed for a reason no cluster has. A realistic
// history -- the cluster is a month old, test-2 was rescheduled a week ago -- made it
// refuse permanently instead. Both facts are pinned here now.
func TestSteadyStateSplitBrain_DemotesASelfElectedOrdinalZero(t *testing.T) {
	v := steadyStateFixture(3, 2)
	r, c, v := wire(t, v,
		createdAt(masterLabeledPod(v, 0, common.RoleMaster), 30*24*time.Hour),
		createdAt(masterLabeledPod(v, 1, common.RoleReplica), 30*24*time.Hour),
		createdAt(masterLabeledPod(v, 2, common.RoleMaster), 7*24*time.Hour),
		replicaConfigMapNaming(v, 2),
	)
	r.InstanceChecker = newRolesChecker(allMasters("test-0", "test-2"))
	rec := &fakeEventRecorder{}
	r.Recorder = rec
	var dialed []string
	wireDemotionTarget(t, r, &dialed)

	_, done, err := r.checkSteadyStateSplitBrain(context.Background(), v)

	require.NoError(t, err)
	assert.True(t, done)
	assert.Equal(t, []string{podAddr(v, "test-0")}, dialed)
	assert.Equal(t, podHost("test", 2), knownMaster(t, c))
	assert.Empty(t, rec.withReason("SplitBrainDemotionRefused"))
}

// The ADR 0008 D10, D11 guard: without a recorded master the check has nothing to demote
// toward, and picking by ordinal would discard the post-failover writes. It must
// refuse -- visibly.
func TestSteadyStateSplitBrain_RefusesWithoutKnownMaster(t *testing.T) {
	v, objs := splitBrainFixture()
	delete(v.Annotations, builder.AnnotationKnownMaster)
	r, _ := newTestReconciler(objs...)
	r.InstanceChecker = newRolesChecker(allMasters("test-0", "test-1"))
	rec := &fakeEventRecorder{}
	r.Recorder = rec
	var dialed []string
	wireDemotionTarget(t, r, &dialed)

	_, done, err := r.checkSteadyStateSplitBrain(context.Background(), v)

	require.NoError(t, err)
	assert.False(t, done)
	assert.Empty(t, dialed, "no REPLICAOF may be issued without a confirmed authority")
	assert.Len(t, rec.withReason("SplitBrainUnresolved"), 1,
		"a refusal must leave a trace, otherwise the split brain is silent again")
}

// A stale annotation naming a pod that has become a replica is not an authority.
func TestSteadyStateSplitBrain_RefusesWhenKnownMasterIsReplica(t *testing.T) {
	v, objs := splitBrainFixture()
	r, _ := newTestReconciler(objs...)
	r.InstanceChecker = newRolesChecker(map[string]string{
		"test-0": common.RoleMaster,
		"test-1": common.RoleReplica,
	})
	rec := &fakeEventRecorder{}
	r.Recorder = rec
	var dialed []string
	wireDemotionTarget(t, r, &dialed)

	_, done, err := r.checkSteadyStateSplitBrain(context.Background(), v)

	require.NoError(t, err)
	assert.False(t, done)
	assert.Empty(t, dialed)
	assert.Len(t, rec.withReason("SplitBrainUnresolved"), 1)
}

// An unreachable recorded master is not an authority either: it may be restarting
// and about to come back with the newer dataset.
func TestSteadyStateSplitBrain_RefusesWhenKnownMasterUnreachable(t *testing.T) {
	v, objs := splitBrainFixture()
	r, _ := newTestReconciler(objs...)
	r.InstanceChecker = newRolesChecker(allMasters("test-0"))
	rec := &fakeEventRecorder{}
	r.Recorder = rec
	var dialed []string
	wireDemotionTarget(t, r, &dialed)

	_, done, err := r.checkSteadyStateSplitBrain(context.Background(), v)

	require.NoError(t, err)
	assert.False(t, done)
	assert.Empty(t, dialed)
	assert.Len(t, rec.withReason("SplitBrainUnresolved"), 1)
}

// The label is only the trigger. A pod that still carries a stale master label
// after a legitimate demotion answers role:slave and must be left alone.
func TestSteadyStateSplitBrain_IgnoresStaleMasterLabel(t *testing.T) {
	v, objs := splitBrainFixture()
	r, _ := newTestReconciler(objs...)
	r.InstanceChecker = newRolesChecker(map[string]string{
		"test-0": common.RoleReplica,
		"test-1": common.RoleMaster,
	})
	var dialed []string
	wireDemotionTarget(t, r, &dialed)

	_, done, err := r.checkSteadyStateSplitBrain(context.Background(), v)

	require.NoError(t, err)
	assert.False(t, done, "a stale label alone is no reason to requeue")
	assert.Empty(t, dialed)
}

// A confirmed second master the operator cannot demote is a lasting condition,
// not a transient one. Ending the pass for it suppressed updateStatus, so the CR
// froze at its last verdict -- typically OK -- while the operator looped on the
// split brain every 15 s with nothing but a log line to show for it.
func TestSteadyStateSplitBrain_UnresolvableRogueKeepsTheStatusWrite(t *testing.T) {
	v, objs := splitBrainFixture()
	r, _ := newTestReconciler(objs...)
	r.InstanceChecker = newRolesChecker(allMasters("test-0", "test-1"))
	rec := &fakeEventRecorder{}
	r.Recorder = rec
	// NewValkeyClientFn stays at the newTestReconciler default, which dials
	// 127.0.0.1 and is refused, so REPLICAOF fails.

	result, done, err := r.checkSteadyStateSplitBrain(context.Background(), v)

	require.NoError(t, err)
	assert.False(t, done,
		"the pass must reach updateStatus so the CR stops reporting a healthy cluster")
	assert.Equal(t, steadyStateRecheckDelay, result.RequeueAfter,
		"reaching updateStatus must not cost the recheck: a ready rogue leaves the phase at OK, "+
			"and nothing else schedules the next pass before the 10 h cache resync")

	warnings := rec.withReason("SplitBrainUnresolved")
	require.Len(t, warnings, 1,
		"a split brain the operator cannot resolve has to be readable off the CR")
	assert.Contains(t, warnings[0].note, "test-1")
}

// --- the stamp lifecycle: spent evidence has to go ---

// Attack A3, and the reason clearing is correctness rather than hygiene. A stamp
// left behind after the operator recorded a master outranks the annotation on the
// next multi-master pass (rule 1 is evidence-first), so the operator would adopt the
// stale pod and REPLICAOF the master it legitimately promoted -- the exact loss the
// stamp exists to prevent, one pass later.
func TestRecordPromotedMaster_ClearsEveryDrainStamp(t *testing.T) {
	v := steadyStateFixture(3, 0)
	r, c, v := wire(t, v,
		drainStamped(masterLabeledPod(v, 0, common.RoleReplica)),
		masterLabeledPod(v, 1, common.RoleMaster),
		drainStamped(masterLabeledPod(v, 2, common.RoleReplica)),
	)

	require.NoError(t, r.recordPromotedMaster(context.Background(), v, podHost("test", 1)))

	assert.Equal(t, podHost("test", 1), knownMaster(t, c))
	assert.Empty(t, podStamp(t, c, "test-0"), "every pod of the cluster, not only the recorded one")
	assert.Empty(t, podStamp(t, c, "test-2"))
}

// A stamp the operator cannot clear must not cost the record. The promotion has
// already happened at that point, so aborting would trade a possible wrong adoption
// later for a certainly unrecorded promotion now.
func TestRecordPromotedMaster_RecordsEvenWhenTheStampClearFails(t *testing.T) {
	v := steadyStateFixture(2, 0)
	objs := []client.Object{
		v,
		masterLabeledPod(v, 0, common.RoleMaster),
		drainStamped(masterLabeledPod(v, 1, common.RoleReplica)),
	}
	r, c := newInterceptedReconciler(interceptor.Funcs{
		Patch: func(_ context.Context, _ client.WithWatch, obj client.Object,
			_ client.Patch, _ ...client.PatchOption) error {
			if _, isPod := obj.(*corev1.Pod); isPod {
				return apierrors.NewInternalError(fmt.Errorf("pod patch rejected"))
			}
			return nil
		},
	}, objs...)

	err := r.recordPromotedMaster(context.Background(), crGet(t, c, "test"), podHost("test", 1))

	require.NoError(t, err, "the promotion is recorded; a leftover stamp is a later risk, not this failure")
	assert.Equal(t, podHost("test", 1), knownMaster(t, c))
	assert.NotEmpty(t, podStamp(t, c, "test-1"), "the fixture must actually have failed to clear")
}

// [REGRESSION] recordPromotedMaster is not the funnel every known-master write goes
// through, so it cannot be the only place the stamps die. persistManualFailoverState
// writes the annotation directly (one Update, for its conflict retry), and the
// completion paths that record no master of their own -- verifyTopologyRestored,
// finalizeMultiReplicaRollingUpdate, handlePostManualFailover -- clear the state
// without ever passing through it. A rolling update could therefore finish with a
// spent stamp still on a pod, where it outranks the annotation the update just wrote
// and hands the next multi-master pass the wrong authority.
//
// clearRollingUpdateState is the one place all of them converge.
func TestClearRollingUpdateState_ClearsEveryDrainStamp(t *testing.T) {
	v := steadyStateFixture(2, 1)
	v.Annotations[annotationRollingUpdateState] = stateManualFailover
	r, c, v := wire(t, v,
		drainStamped(masterLabeledPod(v, 0, common.RoleReplica)),
		drainStamped(masterLabeledPod(v, 1, common.RoleMaster)),
	)

	require.NoError(t, r.clearRollingUpdateState(context.Background(), v))

	assert.Empty(t, podStamp(t, c, "test-0"))
	assert.Empty(t, podStamp(t, c, "test-1"))
	assert.Equal(t, podHost("test", 1), knownMaster(t, c), "the record itself is untouched")
}

// And the placement that makes it safe. checkAndHandleRollingUpdate calls
// clearRollingUpdateState on every pass that reports Completed -- including the
// passes where no update was running at all -- and it runs before
// checkSteadyStateSplitBrain in the same reconcile. Clearing above the early return
// would therefore delete the stamp of a fresh drain in the pass before the check
// that exists to read it, which would quietly disable the whole design.
func TestClearRollingUpdateState_KeepsTheStampsWhenNoUpdateWasRunning(t *testing.T) {
	v := steadyStateFixture(2, 0)
	r, c, v := wire(t, v, drainStamped(masterLabeledPod(v, 1, common.RoleMaster)))

	require.NoError(t, r.clearRollingUpdateState(context.Background(), v))

	assert.NotEmpty(t, podStamp(t, c, "test-1"),
		"a pass with no rolling-update state must leave the evidence for the split-brain check")
}

// Attack A4. The stamp is a pod annotation the operator writes to a running pod, so
// it must not make that pod look out of date -- a rolling update triggered by
// evidence of a drain would be a spectacular way to lose the thing it protects.
func TestPodNeedsUpdate_IgnoresTheDrainStamp(t *testing.T) {
	pod := &corev1.Pod{
		ObjectMeta: metav1.ObjectMeta{
			Name: "test-1",
			Annotations: map[string]string{
				builder.AnnotationConfigHash:     "cfg",
				builder.AnnotationPodSpecHash:    "spec",
				common.AnnotationDrainPromotedAt: time.Now().UTC().Format(time.RFC3339),
			},
		},
		Spec: corev1.PodSpec{Containers: []corev1.Container{
			{Name: builder.ValkeyContainerName, Image: "valkey/valkey:8.0"},
		}},
	}

	assert.False(t, podNeedsUpdate(pod, "valkey/valkey:8.0", "", "cfg", "spec", "", nil),
		"an extra annotation is not spec drift")
	assert.True(t, podNeedsUpdate(pod, "valkey/valkey:8.0", "", "cfg", "other", "", nil),
		"and the control: a changed pod-spec hash still is")
}

// --- the plumbing, and the recheck on the way back out ---

// The wiring: without this the check exists but never runs.
func TestPostRollingUpdateChecks_RunsSteadyStateCheck(t *testing.T) {
	v, objs := splitBrainFixture()
	r, _ := newTestReconciler(objs...)
	r.InstanceChecker = newRolesChecker(allMasters("test-0", "test-1"))
	var dialed []string
	wireDemotionTarget(t, r, &dialed)

	result, done, err := r.handlePostRollingUpdateChecks(context.Background(), v)

	require.NoError(t, err)
	assert.True(t, done)
	assert.Equal(t, steadyStateRecheckDelay, result.RequeueAfter)
	assert.Equal(t, []string{podAddr(v, "test-0")}, dialed)
}

// masterLabeledStsPod builds a pod that is both up to date with respect to the
// persisted StatefulSet template and carries the label set the -rw Service selects
// on, so a full reconcileWorkload pass reaches the steady-state check without
// starting a rolling update on the way.
func masterLabeledStsPod(v *vkov1.Valkey, sts *appsv1.StatefulSet, ordinal int, role string) *corev1.Pod {
	pod := podFromStsTemplate(v, sts, ordinal)
	for k, val := range common.PodLabels(v, common.ComponentValkey, pod.Name, role, nil) {
		pod.Labels[k] = val
	}
	return pod
}

// checkSteadyStateSplitBrain deliberately does not end the pass for a split brain
// it cannot resolve, so that updateStatus still runs. That costs it the only
// requeue it had: a ready rogue leaves the phase at OK, reconcileWorkload then
// returns no requeue of its own, and the CR watch is generation-gated with no Pod
// watch behind it — the next look is the 10 h cache resync. The recheck therefore
// travels as a non-terminal Result, which is worth nothing unless the caller
// applies it.
func TestReconcileWorkload_CarriesTheSplitBrainRecheck(t *testing.T) {
	const name = "recheck"
	v := newTestValkey(name, testNamespace, func(v *vkov1.Valkey) { v.Spec.Replicas = 2 })
	v.Annotations = map[string]string{builder.AnnotationKnownMaster: podHost(name, 1)}
	sts := stsForValkey(v)

	r, c := newTestReconciler(v, sts,
		masterLabeledStsPod(v, sts, 0, common.RoleMaster),
		masterLabeledStsPod(v, sts, 1, common.RoleMaster),
	)
	r.InstanceChecker = newRolesChecker(allMasters(name+"-0", name+"-1"))
	// NewValkeyClientFn stays at the newTestReconciler default, which dials
	// 127.0.0.1 and is refused, so the rogue keeps refusing the REPLICAOF.

	result, err := r.reconcileWorkload(context.Background(), crGet(t, c, name))

	require.NoError(t, err)
	assert.Equal(t, steadyStateRecheckDelay, result.RequeueAfter,
		"a split brain the operator cannot resolve must not wait for the cache resync")
	assert.Equal(t, vkov1.ValkeyPhaseOK, crGet(t, c, name).Status.Phase,
		"and the requeue must be the check's own, not a side effect of an unhealthy phase")
}

// The counterpart: a healthy cluster still ends its pass with no requeue at all.
func TestReconcileWorkload_HealthyClusterKeepsNoRequeue(t *testing.T) {
	const name = "healthy"
	v := newTestValkey(name, testNamespace, func(v *vkov1.Valkey) { v.Spec.Replicas = 2 })
	v.Annotations = map[string]string{builder.AnnotationKnownMaster: podHost(name, 0)}
	sts := stsForValkey(v)

	r, c := newTestReconciler(v, sts,
		masterLabeledStsPod(v, sts, 0, common.RoleMaster),
		masterLabeledStsPod(v, sts, 1, common.RoleReplica),
	)
	r.InstanceChecker = newRolesChecker(map[string]string{
		name + "-0": common.RoleMaster,
		name + "-1": common.RoleReplica,
	})

	result, err := r.reconcileWorkload(context.Background(), crGet(t, c, name))

	require.NoError(t, err)
	assert.Zero(t, result.RequeueAfter, "the pending result must stay zero on the healthy path")
	assert.Equal(t, vkov1.ValkeyPhaseOK, crGet(t, c, name).Status.Phase)
}

// The refusal is a lasting condition, so it has to behave like the unresolvable
// rogue does across the whole pass: the status write still happens, and the recheck
// survives the trip back through reconcileWorkload instead of waiting for the 10 h
// cache resync.
//
// The fixture is the missed-drain shape, and the pass publishes the replica
// ConfigMap itself on the way in, so the structural rule reads the real thing.
func TestReconcileWorkload_CarriesTheRefusedDemotionRecheck(t *testing.T) {
	const name = "refused"
	v := newTestValkey(name, testNamespace, func(v *vkov1.Valkey) { v.Spec.Replicas = 2 })
	v.Annotations = map[string]string{builder.AnnotationKnownMaster: podHost(name, 0)}
	sts := stsForValkey(v)

	r, c := newTestReconciler(v, sts,
		masterLabeledStsPod(v, sts, 0, common.RoleMaster),
		masterLabeledStsPod(v, sts, 1, common.RoleMaster),
	)
	r.InstanceChecker = newRolesChecker(allMasters(name+"-0", name+"-1"))
	// A REPLICAOF that would succeed, so the requeue cannot be mistaken for the
	// one a merely failing demotion produces.
	var dialed []string
	wireDemotionTarget(t, r, &dialed)

	result, err := r.reconcileWorkload(context.Background(), crGet(t, c, name))

	require.NoError(t, err)
	assert.Empty(t, dialed, "the guard has to hold across a full pass, not just in isolation")
	assert.Equal(t, steadyStateRecheckDelay, result.RequeueAfter,
		"a demotion the operator refuses must not wait for the cache resync either")
	assert.Equal(t, vkov1.ValkeyPhaseOK, crGet(t, c, name).Status.Phase,
		"and the requeue must be the check's own, not a side effect of an unhealthy phase")
}

// --- the two helpers the structural rule stands on ---

func TestPodOrdinal(t *testing.T) {
	cases := map[string]int{
		"test-0":          0,
		"test-12":         12,
		"my-valkey-3":     3,
		"noordinal":       -1,
		"test-":           -1,
		"test-abc":        -1,
		"test-1-notanint": -1,
	}
	for name, want := range cases {
		assert.Equal(t, want, podOrdinal(name), name)
	}
}

// The predicate reads "the init script could not have given this pod the role".
// An empty cmMaster means the ConfigMap could not be read, and it deliberately
// compares unequal: the callers that must fail closed on a destructive action rely
// on that, and the one that must not adopt on missing evidence checks the flag
// replicaConfigMaster returns alongside it.
func TestCouldNotHaveSelfElected(t *testing.T) {
	assert.True(t, couldNotHaveSelfElected("test-1", "test-0"))
	assert.False(t, couldNotHaveSelfElected("test-0", "test-2"),
		"ordinal 0 is the init script's unconditional fallback")
	assert.False(t, couldNotHaveSelfElected("test-1", "test-1"),
		"the ADR 0008 D8, D9 self-claim: the ConfigMap names this very pod")
	assert.True(t, couldNotHaveSelfElected("test-1", ""))
}

func TestReplicaConfigMaster(t *testing.T) {
	v := steadyStateFixture(2, 1)
	r, _, v := wire(t, v, replicaConfigMapNaming(v, 1))

	name, known := r.replicaConfigMaster(context.Background(), v)

	assert.True(t, known)
	assert.Equal(t, "test-1", name, "the first DNS label of the replicaof target")
}

func TestReplicaConfigMaster_UnknownWhenTheConfigMapIsAbsent(t *testing.T) {
	v := steadyStateFixture(2, 1)
	r, _, v := wire(t, v)

	name, known := r.replicaConfigMaster(context.Background(), v)

	assert.False(t, known)
	assert.Empty(t, name)
}

// The fail-closed reading of the creation order on the side that still uses it. The
// recorded authority answers role:master but its Pod object cannot be read, so the
// operator knows nothing about an order and must not manufacture a refusal out of
// that ignorance -- the structural rule alone decides, and here it does not fire
// either (the authority is not pod-0), so the demotion proceeds.
func TestSteadyStateSplitBrain_AnUnreadableRecordedPodIsNotACreationOrder(t *testing.T) {
	v := steadyStateFixture(3, 1)
	r, c, v := wire(t, v,
		createdAt(masterLabeledPod(v, 0, common.RoleMaster), 30*24*time.Hour),
		createdAt(masterLabeledPod(v, 2, common.RoleMaster), 30*24*time.Hour),
		replicaConfigMapNaming(v, 1),
	)
	// test-1 answers as the master it is recorded as, but its Pod object is gone.
	r.InstanceChecker = newRolesChecker(allMasters("test-0", "test-1", "test-2"))
	rec := &fakeEventRecorder{}
	r.Recorder = rec
	var dialed []string
	wireDemotionTarget(t, r, &dialed)

	_, done, err := r.checkSteadyStateSplitBrain(context.Background(), v)

	require.NoError(t, err)
	assert.True(t, done)
	assert.ElementsMatch(t, []string{podAddr(v, "test-0"), podAddr(v, "test-2")}, dialed)
	assert.Equal(t, podHost("test", 1), knownMaster(t, c))
	assert.Empty(t, rec.withReason("SplitBrainDemotionRefused"))
}

// --- what happens when the API server does not cooperate ---
//
// Every branch below is the check running against a failing API server. The rule
// they share: missing information is never read as "nothing to do". A demotion is a
// REPLICAOF, so acting on a half-read cluster is the one outcome worse than not
// acting at all -- but silently reporting success is the other, because then no
// later pass looks again.

// failPodList makes every Pod List fail, the way a torn-down informer or an
// unavailable API server does. Reads of other kinds still work.
func failPodList(err error) interceptor.Funcs {
	return interceptor.Funcs{
		List: func(ctx context.Context, c client.WithWatch, list client.ObjectList,
			opts ...client.ListOption) error {
			if _, ok := list.(*corev1.PodList); ok {
				return err
			}
			return c.List(ctx, list, opts...)
		},
	}
}

// The pod List is how the check learns how many masters there are. An empty result
// and a failed read look the same to a caller that ignores the error, and the empty
// result is the no-op path -- so a swallowed failure would turn every API outage
// into "no split brain here" forever.
func TestSteadyStateSplitBrain_ListFailureFailsThePass(t *testing.T) {
	v := steadyStateFixture(2, 1)
	r, c := newInterceptedReconciler(
		failPodList(apierrors.NewServiceUnavailable("etcd leader changed")),
		v, masterLabeledPod(v, 0, common.RoleMaster), masterLabeledPod(v, 1, common.RoleMaster))
	checker := newRolesChecker(allMasters("test-0", "test-1"))
	r.InstanceChecker = checker
	rec := &fakeEventRecorder{}
	r.Recorder = rec
	var dialed []string
	wireDemotionTarget(t, r, &dialed)

	result, done, err := r.checkSteadyStateSplitBrain(context.Background(), crGet(t, c, "test"))

	require.Error(t, err, "an unreadable cluster must not pass as a healthy one")
	assert.Contains(t, err.Error(), "listing master-labeled pods")
	assert.Contains(t, err.Error(), "etcd leader changed", "the cause must survive the wrapping")
	assert.True(t, done, "the caller returns the error, so the rest of the pass must not run")
	assert.Zero(t, result.RequeueAfter, "the rate limiter owns the retry, not a fixed delay")
	assert.Empty(t, dialed, "nothing is demoted on the strength of a failed read")
	assert.Equal(t, 0, checker.probes)
	assert.Equal(t, podHost("test", 1), knownMaster(t, c), "the recorded authority is untouched")
}

// The adoption is recorded before anything is demoted, and the order is load
// bearing: demoting toward a pod the CR does not name would have the next pass read
// the old annotation back and demote in the opposite direction -- once in each
// direction is both datasets gone. A rejected CR write therefore has to stop the
// consolidation dead and come back later.
func TestSteadyStateSplitBrain_RejectedAdoptionDemotesNothing(t *testing.T) {
	_, objs := splitBrainFixture()
	drainStamped(objs[1].(*corev1.Pod)) // pod-0, which the annotation does not name
	attempts := 0
	r, c := newInterceptedReconciler(rejectKnownMasterWrite(podHost("test", 0), &attempts), objs...)
	r.InstanceChecker = newRolesChecker(allMasters("test-0", "test-1"))
	rec := &fakeEventRecorder{}
	r.Recorder = rec
	var dialed []string
	wireDemotionTarget(t, r, &dialed)

	result, done, err := r.checkSteadyStateSplitBrain(context.Background(), crGet(t, c, "test"))

	require.NoError(t, err, "a rejected annotation write is retried, not surfaced as a pass failure")
	assert.False(t, done)
	assert.Equal(t, steadyStateRecheckDelay, result.RequeueAfter,
		"the split brain is still there, so the check has to come back on its own")
	assert.Equal(t, 1, attempts, "the write was attempted")
	assert.Empty(t, dialed,
		"an unrecorded adoption must demote nobody: the next pass would read the old annotation back")
	assert.Equal(t, podHost("test", 1), knownMaster(t, c), "the API server keeps the previous value")
	assert.Empty(t, rec.withReason("MasterAdopted"), "nothing was adopted, so nothing may be announced")
	assert.NotEmpty(t, podStamp(t, c, "test-0"),
		"only a recorded adoption spends the stamp; the retry needs the evidence again")
}

// A stamp is not evidence on its own: it says a drain promoted this pod once, and a
// pod that has since stopped answering role:master no longer holds anything the
// consolidation has to protect. Counting the stamp anyway would adopt a replica --
// or an unreachable pod -- as the master and republish the replica ConfigMap toward
// it, which is how the returning peers would be pointed at a pod that is not one.
func TestSteadyStateSplitBrain_StampOnAPodThatNoLongerAnswersMasterIsNotEvidence(t *testing.T) {
	tests := []struct {
		name  string
		roles map[string]string
	}{
		{
			name: "the stamped pod has become a replica",
			roles: map[string]string{
				"test-0": common.RoleReplica,
				"test-1": common.RoleMaster,
			},
		},
		{
			// An absent name is unreachable for newRolesChecker, so the probe errors.
			name:  "the stamped pod does not answer at all",
			roles: map[string]string{"test-1": common.RoleMaster},
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			_, objs := splitBrainFixture()
			drainStamped(objs[1].(*corev1.Pod)) // pod-0 carries the label and the stamp
			r, c, v := wire(t, objs...)
			r.InstanceChecker = newRolesChecker(tt.roles)
			rec := &fakeEventRecorder{}
			r.Recorder = rec
			var dialed []string
			wireDemotionTarget(t, r, &dialed)

			_, _, err := r.checkSteadyStateSplitBrain(context.Background(), v)

			require.NoError(t, err)
			assert.Equal(t, podHost("test", 1), knownMaster(t, c),
				"a stamp on a pod that gave up the role must not move the recorded authority")
			assert.Empty(t, rec.withReason("MasterAdopted"))
			assert.Empty(t, dialed,
				"the pod is no longer a confirmed master, so there is nothing to demote either")
			assert.NotEmpty(t, podStamp(t, c, "test-0"),
				"no adoption happened, so the stamp is not spent")
		})
	}
}

// clearDrainStamps runs after the annotation was already written. Its List can fail
// like any other, and when it does the recording is still done -- the stamp merely
// outlives its promotion, which the caller documents as a degradation. Failing the
// promotion over it would be strictly worse: the annotation is persisted, so the
// caller would report an error for work that succeeded.
func TestRecordPromotedMaster_SurvivesAFailedStampCleanup(t *testing.T) {
	v := steadyStateFixture(2, 0)
	pod1 := drainStamped(masterLabeledPod(v, 1, common.RoleMaster))
	r, c := newInterceptedReconciler(
		failPodList(apierrors.NewServiceUnavailable("informer torn down")),
		v, masterLabeledPod(v, 0, common.RoleReplica), pod1)

	err := r.recordPromotedMaster(context.Background(), crGet(t, c, "test"), podHost("test", 1))

	require.NoError(t, err, "the promotion is recorded; the stamp cleanup is best-effort")
	assert.Equal(t, podHost("test", 1), knownMaster(t, c))
	assert.NotEmpty(t, podStamp(t, c, "test-1"),
		"the stamp could not be cleared, which is the degradation the log warns about")
}

// --- the replica ConfigMap parse ---
//
// replicaConfigMaster reads the file the init script reads. Its second return value
// says whether the published master could be determined at all, and callers turn a
// false into "no positive justification", which refuses a demotion. A parse that
// answered ("", true) for a file it did not understand would instead claim the
// ConfigMap names nobody -- and that claim exonerates every pod with ordinal > 0.

func TestReplicaConfigMaster_ParseOutcomes(t *testing.T) {
	tests := []struct {
		name      string
		data      string
		wantName  string
		wantKnown bool
		why       string
	}{
		{
			name:      "a directive naming a pod",
			data:      "port 6379\nreplicaof " + podHost("test", 2) + " 6379\n",
			wantName:  "test-2",
			wantKnown: true,
			why:       "the pod name is what couldNotHaveSelfElected compares against",
		},
		{
			name:      "no replicaof directive at all",
			data:      "port 6379\nappendonly yes\n",
			wantKnown: false,
			why:       "a master config names nobody, and that is not knowledge about a replica",
		},
		{
			name:      "the directive is present but carries no host",
			data:      "port 6379\nreplicaof \n",
			wantKnown: false,
			why:       "a truncated directive is unparseable, not an answer",
		},
		{
			name:      "an empty ConfigMap",
			data:      "",
			wantKnown: false,
			why:       "nothing published means nothing known",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			v := steadyStateFixture(2, 0)
			cm := &corev1.ConfigMap{
				ObjectMeta: metav1.ObjectMeta{
					Name:      builder.ReplicaConfigMapName(v),
					Namespace: testNamespace,
				},
				Data: map[string]string{builder.ValkeyConfigKey: tt.data},
			}
			controllerRefTo(v, cm)
			r, _ := newTestReconciler(v, cm)

			name, known := r.replicaConfigMaster(context.Background(), v)

			assert.Equal(t, tt.wantKnown, known, tt.why)
			assert.Equal(t, tt.wantName, name)
		})
	}
}
